{
 "title": "NVME",
 "description": "Detailed overview of the NVME cli smartlog output",
 "tags": [
  "NVME",
  "Storage",
  "E4"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(node_uname_info,cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(nvme_nvmecli{cluster_name=\"$cluster_name\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(nvme_power_on_hours_total{instance=~\"$node\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "NVME Disks Dashboard",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "# NVME Metrics\n\nThis dashboard visualizes the metrics exported by a custom exporter inspired by the [Prometheus Node Exporter \"nvme\" collector and \"text file collector\"](https://github.com/prometheus/node_exporter#textfile-collector), uses a bash script running on scraped instances which parses the results of the command `nvme smart-log` for each NVME device discovered.\n\nFor metrics explanation refer to the [NVME Express specifications](https://nvmexpress.org/wp-content/uploads/NVM-Express-Base-Specification-2.0b-2021.12.18-Ratified.pdf), figure \"207\" at Page 180.\n\n## How to use this dashboard\n\n### Help Information\n\nEach visualization displays a \"information\" link on the top left which explains what is being displayed, if any thresholds are applied and how they are implemented.\n\n### Variables\n\nOn the top of the page it is possible to select \"templated\" variables that helps in scoping the results of the visualizations.\n\nSome of these variables are templated as well by other variables.\n\n - **datasource**: The Prometheus Datasource to gather the metrics from.\n - **cluster_name**: The name of the cluster to which the node belongs, this is usually a static label applied to the scraper job.\n - **node**: The node where the metrics are collected from.\n - **device**: The NVME devices discovered on the given host.\n\n Some variables allow multiple selections and \"All\" option.\n\n ### Repetitions\n\n Selecting multiple variables values will result in visualizations expansion by the number of values:\n\n - **node**: The hosts will expand the graphs inside the rows in the same logic.\n - **device**: The device will expand inside the same graph."
     }
    }
   ]
  },
  {
   "title": "Node $node Alerts and Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Warnings Total",
     "type": "stat",
     "description": "This field indicates critical warnings for the state of the controller. Each bit  corresponds to a critical warning type; multiple bits may be set to ‘1’. If a bit is cleared to ‘0’, then that critical warning does not apply. Critical warnings may result in an asynchronous event notification to the host. Bits in this field represent the current associated state and are not persistent.\nNOTE: The metric representation is in Decimal and we do not account for all 32 combinations in the thresholds, they are simbly set based on the MSB\n\n- No Bit set, metric val 0, color green: No Critical Warnings\n- Bit 0, metric val 1, color turquoise: Available Spare is below Threshold\n- Bit 1, metric val 2, color yellow: Temperature has exceeded Threshold\n- Bit 2, metric val 4, color orange: Reliability is degraded due to excessive media or internal errors\n- Bit 3, metric val 8, color purple: Media is placed in Read- Only Mode\n- Bit 4, metric val 16, color red: Volatile Memory Backup System has failed (e.g., enhanced power loss capacitor test failure) ",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_critical_warning_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "NVME Critical Warnings Total Over Time",
     "type": "timeseries",
     "description": "NVME SMART metric critical_warning_total",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate (nvme_critical_warning_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Media and Data Integrity Errors",
     "type": "stat",
     "description": "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field. Errors introduced as a result of a Write Uncorrectable command (refer to the NVM Command Set specification) may or may not be included in this field.\nSince this metric accumulates over time we do not set \"real\" thresholds and the counter becomes violet when above 0.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_media_errors_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Number of Error Information Log Entries",
     "type": "stat",
     "description": "Contains the number of Error Information log entries over the life of the controller.\nSince this metric accumulates over time we do not set \"real\" thresholds and the counter becomes violet when above 0.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_num_err_log_entries_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Media and Data Integrity Errors Over Time",
     "type": "timeseries",
     "description": "Contains the overtime view of the Media and Data Integrity errors metric, no rate is calculated.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nvme_media_errors_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Number of Error Information Log Entries Over Time",
     "type": "timeseries",
     "description": "Contains the overtime view of the Number of Error Information Log Entries metric, no rate is calculated.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nvme_num_err_log_entries_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "NVME CLI Version",
     "type": "stat",
     "description": "Reports the version of the `nvme-cli` installed on the scraped instances.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_nvmecli{instance=~\"[[node]]\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "NVME metrics collection time",
     "type": "stat",
     "description": "NVME metrics are collected via \"text file Node exporter\", this metric reports the time the metrics have been collected by the local cronjob.",
     "gridPos": { "h": 3, "w": 4, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_metrics_completion_time{instance=~\"[[node]]\"} * 1000"
      }
     ]
    },
    {
     "title": "Elapsed NVME metrics collection time",
     "type": "stat",
     "description": "NVME metrics are collected via \"text file Node exporter\", this metric reports how long ago the letrics have been collected by the local cronjob.",
     "gridPos": { "h": 3, "w": 5, "x": 7, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_metrics_completion_time{instance=~\"[[node]]\"} * 1000"
      }
     ]
    },
    {
     "title": "Disk Info",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_nvme_info{instance=~\"$node\", device=~\"(^nvme[0-9]+$|^sd[a-z]+$)\"}"
      }
     ]
    },
    {
     "title": "Unsafe Shutdowns",
     "type": "stat",
     "description": "NVME metrics are collected via \"text file Node exporter\", this metric reports how long ago the letrics have been collected by the local cronjob.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_unsafe_shutdowns_total{instance=~\"[[node]]\", device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node Disk Endurance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage Used Ratio",
     "type": "gauge",
     "description": "Contains a vendor specific estimate of the percentage of NVM subsystem life used based on the actual usage and the manufacturer’s prediction of NVM life. A value of 100 indicates that the estimated endurance of the NVM in the NVM subsystem has been consumed, but may not indicate an NVM subsystem failure. The value is allowed to exceed 100. This value shall be updated \nonce per power-on hour (when the controller is not in a sleep state).\n\nThe Gauge will turn:\n- red 100%\n- yellow 80%",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_percentage_used_ratio{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Available Spare Ratio",
     "type": "gauge",
     "description": "Contains a normalized percentage (0% to 100%) of the remaining spare capacity available.\nThe gauge thresholds are based on the reported metric \"spare threshold value\" of 10%, therefore:\n- above 20% green\n- between 10% and 20% yellow\n- below 10% red\n-\n-",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_available_spare_ratio{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Endurance group Critial Warnings",
     "type": "stat",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_endurance_grp_critical_warning_summary{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Available Spare Threshold Ratio",
     "type": "stat",
     "description": "When the Available Spare falls below the threshold indicated in this field, an asynchronous event completion may occur. The value is indicated as a normalized percentage (0% to 100%).",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_available_spare_threshold_ratio{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node Disks Vitals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Powercycles Total",
     "type": "stat",
     "description": "Contains the number of power cycles",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_power_cycles_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Power ON Time",
     "type": "stat",
     "description": " Contains the number of power-on hours. This may not include time that the controller was powered and in a non-operational power state.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_power_on_hours_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "description": "Contains a value corresponding to a temperature in Celsius that represents the current composite temperature of the controller and namespace(s) associated with that controller. Warning and critical overheating composite temperature threshold values are reported by the WCTEMP and CCTEMP fields, these are dependant on the disk model and obtained via `smartctl` command, therefore:\n\n- below 72C green\n- between 72C and 85C yellow\n- above 85C red",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_temperature_celsius{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Temperature Over Time",
     "type": "timeseries",
     "description": "Temperature over time, refer to the gauge graph for the help.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "nvme_temperature_celsius{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node Disks Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Busy Time minutes",
     "type": "stat",
     "description": "Contains the amount of time the controller is busy with I/O commands. The controller is busy when there is a command outstanding to an I/O Queue (specifically, a command was issued via an I/O Submission Queue Tail doorbell write and the corresponding completion queue entry has not been posted yet to the associated I/O Completion Queue).\nThis value is reported in minutes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_controller_busy_time_seconds{instance=~\"[[node]]\", device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Controller Busy Time per seconds",
     "type": "timeseries",
     "description": "Contains a rate per second, based on the metric \"controller busy time minutes\" and the selected rate interval.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nvme_controller_busy_time_seconds{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Data Units Read",
     "type": "stat",
     "description": "Contains the number of 512 byte data units the host has read from the  controller as part of processing a SMART Data Units Read Command; this value does not  include metadata. This value is reported in thousands (i.e., a value of 1 corresponds to 1,000 \nunits of 512 bytes read) and is rounded up (e.g., one indicates that the number of 512 byte data units read is from 1 to 1,000, three indicates that the number of 512 byte data units read is from 2,001 to 3,000).",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_data_units_read_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Read Commands per",
     "type": "stat",
     "description": "Contains the number of SMART Host Read Commands completed by the controller.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_host_read_commands_total{instance=~\"[[node]]\",device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Read Bytes per Second",
     "type": "timeseries",
     "description": "Contains the per second rate over the selected rate interval for the metric \"Data Units Read\" converted to byte.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(nvme_data_units_read_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval]) * 512000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Read Commands per Second",
     "type": "timeseries",
     "description": "Contains the per second rate, based on the selected rate interval, for the \"Host Read Commands\" metric",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(nvme_host_read_commands_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Read IO size per Second",
     "type": "timeseries",
     "description": "Contains the per second rate over the selected rate interval of the calculated IO size obtained dividing the Read Units for the Host Read Commands rates ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "(rate(nvme_data_units_read_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval]) / rate(nvme_host_read_commands_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])) * 512000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Data Units Written for $node",
     "type": "stat",
     "description": "Contains the number of 512 byte data units the host has written to the controller as part of processing a User Data Out Command; this value does not include metadata. This value is reported in thousands (i.e., a value of 1 corresponds to 1,000 units of 512 bytes written) and is rounded up (e.g., one indicates that the number of 512 byte data units written is from 1 to 1,000, three indicates that the number of 512 byte data units written is from 2,001 to 3,000).",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_data_units_written_total{device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Write Commands per Second for $node",
     "type": "stat",
     "description": "NVME SMART metric data_units_read_total",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvme_host_write_commands_total{device=~\"[[device]]\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Write Bytes Total for $node",
     "type": "timeseries",
     "description": "Displays the amount of data written on the disks in a timeframe (offset) specified by the rate variable value of $rate  ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(nvme_data_units_written_total{instance=~\"[[node]]\",device=~\"[[device]]\"}offset $__rate_interval) * 512000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Write Bytes per Second for $node",
     "type": "timeseries",
     "description": "Contains the per second rate over the selected rate interval for the metric \"Data Units Write\" converted to byte.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(nvme_data_units_written_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval]) * 512000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Write IO size per Second for $node",
     "type": "timeseries",
     "description": "Contains the per second rate over the selected rate interval of the calculated IO size obtained dividing the Write Units for the Host Write Commands rates ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(nvme_data_units_written_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval]) / rate(nvme_host_write_commands_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])) * 512000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Host Write Commands per Second for $node",
     "type": "timeseries",
     "description": "Contains the rate per second, based on the selected rate interval, for the metric \"Host Write Commands\"",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(nvme_host_write_commands_total{instance=~\"[[node]]\",device=~\"[[device]]\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}